### ISSUE TITLE
`/daily/` with no argument could return the word of the day

### ISSUE THREAD

**Issue by jolitti** [awsare/Wordle-API#1]
Hello, I wanted to create a wordle app and i discovered this extremely convenient API, the only thing i think is missing is a way to get a fixed word for the day (without having to calculate the number of days elapsed since day 1).

Would it be doable to update the API such that `https://thatwordleapi.azurewebsites.net/daily/` would return the word of the day?

Thanks for the attention

**Comment by awsare** [comment]
Sure, thanks for reaching out. I will work on this feature in the next few days.

**Comment by awsare** [comment]
I just added the feature, let me know if you would like anything else.

**Comment by jolitti** [comment]
Thank you! The only other problem I'm having is that I'm trying to use the API via the arduino esp8266 HTTP client library, and when I perform a GET request with it I get a 301 error. Is the API accessible via HTTP or only via HTTPS?

**Comment by awsare** [comment]
I just changed it, tell me if that works.

**Comment by jolitti** [comment]
It works correctly, you have my thanks. Do you have a tip jar?
